services:
  - type: web
    name: school-app
    env: python
    buildCommand: pip install -r backend/requirements.txt
    startCommand: uvicorn backend.main:app --host 0.0.0.0 --port 10000
    plan: free
    autoDeploy: true
